# Generated by Django 4.0.5 on 2022-08-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=70)),
                ('Password', models.CharField(max_length=70)),
                ('Contact_number', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=70)),
                ('date', models.CharField(max_length=70)),
                ('approve_name', models.CharField(max_length=70)),
                ('request_time', models.CharField(max_length=70)),
            ],
        ),
    ]
